# Generated by Django 3.0.2 on 2020-01-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='composer',
            field=models.CharField(default='none', max_length=250),
        ),
        migrations.AlterField(
            model_name='piece',
            name='title',
            field=models.CharField(default='untitled', max_length=250),
        ),
    ]
