# Generated by Django 3.0.2 on 2020-03-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_auto_20200122_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='slug',
            field=models.SlugField(default='slug', unique=True),
            preserve_default=False,
        ),
    ]
