# Generated by Django 3.0.2 on 2020-03-07 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_piece_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piece',
            old_name='user',
            new_name='username',
        ),
    ]
