# Generated by Django 3.0.2 on 2020-03-07 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_auto_20200307_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piece',
            old_name='username',
            new_name='user',
        ),
    ]
