# Generated by Django 3.0.2 on 2020-03-07 21:49

from django.db import migrations, models
import generator.models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_auto_20200307_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='file',
            field=models.FileField(blank=True, upload_to=generator.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='piece',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
