# Generated by Django 3.0.2 on 2020-03-07 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0006_auto_20200307_2149'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Piece',
            new_name='Composition',
        ),
    ]
