# Generated by Django 3.0.2 on 2020-03-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0008_auto_20200309_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='beatunitdata',
            field=models.CharField(default=4, max_length=4),
        ),
        migrations.AddField(
            model_name='composition',
            name='divisiondata',
            field=models.CharField(choices=[('2', '2'), ('4', '4'), ('8', '8'), ('16', '16')], default='4', max_length=2),
        ),
        migrations.AddField(
            model_name='composition',
            name='notedata',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='composition',
            name='tempodata',
            field=models.IntegerField(default=120),
        ),
    ]
