# Generated by Django 3.0.2 on 2020-03-10 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0009_auto_20200310_0417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='composition',
            old_name='beatunitdata',
            new_name='beatunit',
        ),
        migrations.RenameField(
            model_name='composition',
            old_name='notedata',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='composition',
            old_name='divisiondata',
            new_name='division',
        ),
        migrations.RenameField(
            model_name='composition',
            old_name='tempodata',
            new_name='tempo',
        ),
        migrations.AddField(
            model_name='composition',
            name='beats',
            field=models.IntegerField(default=128),
        ),
        migrations.AlterField(
            model_name='composition',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NoteObject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('duration', models.DecimalField(choices=[(4, '16'), (3, '12'), (2, '8'), (1.5, '6'), (1, '1'), (0.75, '3'), (0.5, '2'), (0.375, '1.5'), (0.25, '1')], decimal_places=3, default=1, max_digits=5)),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generator.Composition')),
            ],
        ),
    ]
