# Generated by Django 3.0.4 on 2020-04-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0026_auto_20200310_0620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composition',
            name='beats',
        ),
        migrations.AlterField(
            model_name='noteobject',
            name='duration',
            field=models.DecimalField(choices=[(4, '16'), (3, '12'), (2, '8'), (1.5, '6'), (1, '4'), (0.75, '3'), (0.5, '2'), (0.375, '1.5'), (0.25, '1')], decimal_places=3, default=1, max_digits=5),
        ),
    ]
