# Generated by Django 3.0.4 on 2020-04-23 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0027_auto_20200423_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteobject',
            name='accidental',
            field=models.CharField(blank=True, choices=[('double-flat', 'double-flat'), ('flat', 'flat'), ('natural', 'natural'), ('sharp', 'sharp'), ('double-sharp', 'double-sharp'), ('', 'none')], default='', max_length=12),
        ),
    ]
