# Generated by Django 3.0.5 on 2020-04-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0029_auto_20200425_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composition',
            name='beatunit',
        ),
        migrations.RemoveField(
            model_name='composition',
            name='division',
        ),
        migrations.RemoveField(
            model_name='noteobject',
            name='octave',
        ),
        migrations.AddField(
            model_name='composition',
            name='meter',
            field=models.CharField(choices=[('2/4', '2/4'), ('3/4', '3/4'), ('4/4', '4/4')], default='4/4', max_length=3),
        ),
        migrations.AddField(
            model_name='noteobject',
            name='order',
            field=models.DecimalField(decimal_places=10, default=1, max_digits=20, max_length=20),
        ),
        migrations.AlterField(
            model_name='noteobject',
            name='accidental',
            field=models.CharField(choices=[('double-flat', 'double-flat'), ('flat', 'flat'), ('natural', 'natural'), ('sharp', 'sharp'), ('double-sharp', 'double-sharp'), ('', 'none')], default='none', max_length=12),
        ),
        migrations.AlterField(
            model_name='noteobject',
            name='duration',
            field=models.DecimalField(choices=[('4', 4), ('3', 3), ('2', 2), ('1.5', 1.5), ('1', 1), ('0.75', 0.75), ('0.5', 0.5), ('0.375', 0.375), ('0.25', 0.25)], decimal_places=3, default=1, max_digits=4, max_length=5),
        ),
        migrations.AlterField(
            model_name='noteobject',
            name='pitch',
            field=models.IntegerField(choices=[('C3', 1), ('D3', 2), ('E3', 3), ('F3', 4), ('G3', 5), ('A3', 6), ('B3', 7), ('C4', 8), ('D4', 9), ('E4', 10), ('F4', 11), ('G4', 12), ('A4', 13), ('B4', 14), ('C5', 15), ('D5', 16), ('E5', 17), ('F5', 18), ('G5', 19), ('A5', 20), ('B5', 21), ('C6', 22)], default=8),
        ),
    ]
