# Generated by Django 3.0.5 on 2020-05-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0030_auto_20200426_0338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composition',
            name='data',
        ),
        migrations.RemoveField(
            model_name='composition',
            name='meter',
        ),
        migrations.AddField(
            model_name='composition',
            name='bar_beat',
            field=models.CharField(default='4', max_length=2),
        ),
        migrations.AddField(
            model_name='composition',
            name='base_duration',
            field=models.CharField(choices=[('2', 2), ('4', 4), ('8', 8), ('16', 16)], default='4', max_length=2),
        ),
        migrations.AlterField(
            model_name='noteobject',
            name='accidental',
            field=models.CharField(choices=[('double-flat', 'double-flat'), ('flat', 'flat'), ('natural', 'natural'), ('sharp', 'sharp'), ('double-sharp', 'double-sharp'), (' ', ' ')], default=' ', max_length=12),
        ),
        migrations.AlterField(
            model_name='noteobject',
            name='duration',
            field=models.CharField(choices=[('4', 4), ('3', 3), ('2', 2), ('1.5', 1.5), ('1', 1), ('0.75', 0.75), ('0.5', 0.5), ('0.375', 0.375), ('0.25', 0.25)], default=1, max_length=5),
        ),
        migrations.AlterField(
            model_name='noteobject',
            name='order',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=10, unique=True),
        ),
        migrations.AlterField(
            model_name='noteobject',
            name='pitch',
            field=models.CharField(choices=[('C3', 1), ('D3', 2), ('E3', 3), ('F3', 4), ('G3', 5), ('A3', 6), ('B3', 7), ('C4', 8), ('D4', 9), ('E4', 10), ('F4', 11), ('G4', 12), ('A4', 13), ('B4', 14), ('C5', 15), ('D5', 16), ('E5', 17), ('F5', 18), ('G5', 19), ('A5', 20), ('B5', 21), ('C6', 22)], default=8, max_length=2),
        ),
    ]
