# Generated by Django 3.0.5 on 2020-05-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0031_auto_20200504_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composition',
            name='file',
        ),
        migrations.RemoveField(
            model_name='noteobject',
            name='accidental',
        ),
        migrations.AddField(
            model_name='composition',
            name='enharmonic',
            field=models.CharField(choices=[('sharp', 'sharp'), ('flat', 'flat')], default='sharp', max_length=5),
        ),
        migrations.AlterField(
            model_name='noteobject',
            name='pitch',
            field=models.CharField(choices=[('rest', 'rest'), ('C6', 'C6'), ('B5', 'B5'), ('A#5', 'A#5'), ('A5', 'A5'), ('G#5', 'G#5'), ('G5', 'G5'), ('F#5', 'F#5'), ('F5', 'F5'), ('E5', 'E5'), ('D#5', 'D#5'), ('D5', 'D5'), ('C#5', 'C#5'), ('C5', 'C5'), ('B4', 'B4'), ('A#4', 'A#4'), ('A4', 'A4'), ('G#4', 'G#4'), ('G4', 'G4'), ('F#4', 'F#4'), ('F4', 'F4'), ('E4', 'E4'), ('D#4', 'D#4'), ('D4', 'D4'), ('C#4', 'C#4'), ('C4', 'C4'), ('B3', 'B3'), ('A#3', 'A#3'), ('A3', 'A3'), ('G#3', 'G#3'), ('G3', 'G3'), ('F#3', 'F#3'), ('F3', 'F3'), ('E3', 'E3'), ('D#3', 'D#3'), ('D3', 'D3'), ('C#3', 'C#3'), ('C3', 'C3')], default='C4', max_length=4),
        ),
    ]
