# Generated by Django 3.0.5 on 2020-05-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0033_auto_20200505_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteobject',
            name='order',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=10),
        ),
    ]
